### ISSUE TITLE
Login screen style

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#5]
It can be aligned much better.

**Comment by mckdev** [comment]
Can you be more specific? It looks good to me.

**Comment by jananihome** [comment]
forgot password and do u have an account can be place much better i think so. But i am not sure where we can. Just have a look, will see it later. Low priority.

**Comment by mckdev** [comment]
I just don't understand what you mean by "aligned much better" and what exactly can be "aligned much better" and also what "much better" means.

**Comment by jananihome** [comment]
i mean like see it takes more width. So eyes need to travel from left to right. Instead of that we can compact it bring them nearer.

**Comment by mckdev** [comment]
Ok will see

**Comment by mckdev** [comment]
Can we leave it like that for now?
![image](https://user-images.githubusercontent.com/17580930/30513182-0ce5f36e-9aff-11e7-8f6a-f7298a4869bd.png)
You don't have to travel with the eyes to the sidebar, this is just if you need help.
The login form is compact enough I think. I would leave for now and improve it with this ticket I just created:
https://github.com/jananihome/Janani-Home/issues/33
In the next version we can implement authentication views more as a popup over the page so that the forms would be centered on the screen and more compact.

**Comment by jananihome** [comment]
ok

**Comment by mckdev** [comment]
Cool, closing this.
