### ISSUE TITLE
Comments 

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#55]
In comments helper name is not displaying.
We have about education 15 or education 15 which redirects to the detail page. Will have unique ID instead of this education need 14 or 15.

New comments should come first every where.

Comments is having like 'Janani Care', change it to 'Janani Home'.

**Comment by mckdev** [comment]
Hi, this is looking pretty bad when I use the uuid, because it soooooo long and ugly.

The uuid is displayed on the detail page after user clicks through so I think we don't need it on the comment page. Can I use need subject instead? That will look nice and will give users meaningful informations about what the comment is about.

For example it would be "about 'For books'" instead of "about 2017/09/22/a6727fa0-f683-4e1c-8875-086ba132d96" which looks just bad.

**Comment by jananihome** [comment]
better can have like this 'user name' about his post. when clicking on this it should redirect him to his post.
 'user name' about his post - this entire thing should be link. Example 'Janani about his post'.

**Comment by mckdev** [comment]
ok
