### ISSUE TITLE
Closed educational need still displays in card view.

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#71]
Closed a educational need from admin side based on users request.

But after closing still exist in card view.

ID - 2017/09/19/861562fe-c16f-42a8-a2fa-aa8a18080827

Name - venkatammal

**Comment by mckdev** [comment]
Did you deactivate it under Profile model too?
You have to go to user profile in admin, and make sure it is not selected under "active educational need". You probably didn't do that so it i still being displayed, because it's active and card view displays all active educational needs.
Please let me know if disabling it in user profile helped.

**Comment by jananihome** [comment]
Yeah now it works fine after I disable it. I am closing it.
