### ISSUE TITLE
NGO registeration

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#73]
**Need form to register NGO**
Fields:
NGO/Comapny/Organization name **
mob 1 **
mob 2
Ph 1 **
Ph2
email **
fax
address 1 **
address 2
Zipcode **
city **
state **
country **
profile pic 
is_active
approved_field (Uneditable)
Area
(For phone, mobile and address try to create dynamically if possible. I know its mere to impossible)

** --> Mandatory

Volunteer profile details same as existing profile details but need to have fields,
is_volunteer
organization_id

**Comment by mckdev** [comment]
Since Django requires us to use the same User model for NGOs as for all other users, we also need to use the same Profile model for them. This is because whenever User object is created or updated, it triggers the post_save receiver functions which update/create a corresponding Profile model.

In order to differentiate account types in this situation, we need to add "is_organization" and "is_volunteer" fields to Profile. Later on we will be checking against those fields to decide which UI to load for each user type.

We will need a separate signup form for NGO, because we need to use a different activation link than for regular users. This is because current activation link takes users to a view with UserCompletionForm and ProfileCompletionForm which has required fields like first name, last name, birth date, gender etc., which are not applicable to organizations.

So for the registration process we need to add/create:
- is_organization and is_volunteer fields under Profile
- additionally all the fields from this ticket which are not there yet (e.g. organization name etc.)
- OrganizationSignUpForm + organization_signup view
- activate_organization view + OrganizationCompletionForm to be filled out after clicking the activation link
- templates for all the above views + the email template

Once we have this in place, we can proceed with building the interface for organizations in another ticket.

**Comment by jananihome** [comment]
Will have one more field for phone and mobile number and we will have additional contact info too. 
Missed zipcode.
Area I dont think its requires. Lets remove it. If I had mentioned any particular use remind me.
Screen design I will share you in whats app.
Need to add status field. For active or in active field. A boolean field.
After registration they should not able to change their organisation name.
Once they register it should come to admin for approval.Only approved organisation should able to add volunteer.
Heading NGO/Organization Name.

**Comment by mckdev** [comment]
Additional phone numbers
![image](https://user-images.githubusercontent.com/17580930/34391564-b2eb3a7a-eb46-11e7-8528-4c03182aa97b.png)

**Comment by mckdev** [comment]
Zip code field
![image](https://user-images.githubusercontent.com/17580930/34391630-413830bc-eb47-11e7-8c54-c547f757fd1a.png)

**Comment by mckdev** [comment]
Added profile image
![image](https://user-images.githubusercontent.com/17580930/34391773-1d97291e-eb48-11e7-8a61-8e9f47786ed6.png)

**Comment by mckdev** [comment]
Added "active" field, by default it is True, but for organizations it is set to False, so that they can be manually approved.

**Comment by mckdev** [comment]
Added city and district:
![image](https://user-images.githubusercontent.com/17580930/34392115-897faae6-eb4a-11e7-8cb8-cb004c8e532f.png)

**Comment by mckdev** [comment]
Updated form headings
![image](https://user-images.githubusercontent.com/17580930/34393111-78b8edf2-eb50-11e7-84e1-976ab15ffd25.png)
